version: '3.8'

services:
  mariadb:
    image: mariadb:10.0
    container_name: teachingopen-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: teachingopen
      MYSQL_USER: teachingopen
      MYSQL_PASSWORD: teachingopen
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  redis:
    image: redis:6
    container_name: teachingopen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    environment:
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru

volumes:
  mariadb_data:
  redis_data:
